#ifndef INCLUDE_I2C_LASER_RANGEFINDER_H_
#define INCLUDE_I2C_LASER_RANGEFINDER_H_

#include "i2c_lld.h"


#define LR_ADDRESS			0b0101001

#define REG_SET_SETTINGS	0x016



#define MODE_SET_SETTINGS	0x001

#endif /* INCLUDE_I2C_LASER_RANGEFINDER_H_ */
